apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-circleci-app # Artifact registry name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-circleci-app  # Artifact registry name
  template:
    metadata:
      labels:
        app: mlops-circleci-app  # Artifact registry name
    spec:
      containers:
      - name: mlops-circleci-app  # Artifact registry name
        image: us-central1-docker.pkg.dev/mlops-circleci/mlops-circleci-app/mlops-circleci-app:latest  # Artifact registry name
        ports:
        - containerPort: 5000  #you can see in application.py file

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-circleci-app  # Artifact registry name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
