version: 2.1 # CircleCI version

executors:  #reusable environemnts for the jobs
  docker-executor:  # means this executor - the app runs inside the docker
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo  #default working directory for the jobs

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    machine: true #executor: docker-executor
    steps:
      - checkout #- setup_remote_docker
      - run:
          name: Authenticate with google cloud
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json 
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Build and Push Image
          command: |
              docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-circleci-app/mlops-circleci-app:latest .
              docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/mlops-circleci-app/mlops-circleci-app:latest

  deploy_to_gke:
    machine: true #executor: docker-executor
    steps:
      - checkout #- setup_remote_docker
      - run:
          name: Install kubectl
          command: |
              curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              sudo mv kubectl /usr/local/bin/
      - run:
          name: Authenticate with google cloud
          command: |
              echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
              gcloud auth activate-service-account --key-file=gcp-key.json
              gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker
      
      - run:
          name: Configure GKE
          command: |
              gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
              kubectl apply -f kubernetes-deployment.yaml

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image

    





